server:
  port: 8081
spring:
  application:
    name: demo
  boot:
    admin:
      client:
        url: http://localhost:${server.port}
        instance:
          service-base-url: http://localhost:${server.port}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.193.101:3306/demos?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#    url: jdbc:mysql://124.223.29.146:3306/demos?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: liu15853087850
  redis:
    database: 0
    host: 192.168.193.101
    port: 6379
    password: liu15853087850
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #SpringBoot更新至2.6.0，swagger就引发了这个bug，加上这个配置来解决
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
mybatis-plus:
  mapper-locations: classpath:**/mapper/*.xml
  #configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

