server:
  port: 8081
spring:
  application:
    name: demo
  boot:
    admin:
      client:
        url: http://localhost:${server.port}
        instance:
          service-base-url: http://localhost:${server.port}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: true #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource: # 通过@DS("dm")注解放到类或方法上来切换数据源
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          # 这里原来是url，现在改为jdbc-url，解决：urljdbcUrl is required with driverClassName错误
          # 是因为这个类导致的：DatasourceConfig
          url: jdbc:mysql://192.168.1.107:3306/demos?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: liu15853087850
        #        dm:
        #          driver-class-name: dm.jdbc.driver.DmDriver
        #          url: jdbc:dm://localhost:5236/DEMOS?useUnicode=true&amp;characterEncoding=UTF-8
        #          username: DEMOS
        #          password: DEMOS@123
        td:
          driver-class-name: com.taosdata.jdbc.rs.RestfulDriver
          url: jdbc:TAOS-RS://192.168.1.107:6041/test?user=root&password=taosdata
        # x-pack
        es:
          driver-class-name: org.elasticsearch.xpack.sql.jdbc.EsDriver
          url: jdbc:es://http://192.168.1.107:9200/?timezone=UTC&page.size=250
  redis:
    database: 0
    host: 192.168.1.107
    port: 6379
    password: liu15853087850
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #SpringBoot更新至2.6.0，swagger就引发了这个bug，加上这个配置来解决
  elasticsearch:
    uris: 192.168.1.107
  kafka:
    bootstrap-servers: 192.168.1.107:9092
    consumer:
      group-id: myGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    zookeeper:
      connect: 192.168.1.107:2181
# spring-boot-admin
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
mybatis-plus:
  mapper-locations: classpath:**/mapper/*.xml
    #configuration:
  #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    accessToken: default_token
    executor:
      appname: xxlJobDemo
      address :
      ip:
      port: 9999
      logpath:
      logretentiondays: 30