server:
  port: 8181
spring:
  application:
    name: provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.107:8848
dubbo:
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: org.example.provider

